game:
  greeting: Greetings young dealer. What shall I call you?
  welcome: "Nice to meet you, %{name}. Here is $%{amount}.00 and some %{drug} to get you started."
  dealer_introduction: 
    "Now that you have that, there is one more thing you will need.\nHere is a plane ticket, and boarding pass good for 30 days.\nThis will allow you to travel to one of 6 specific cities\nYou will also need this bag to carry stuff in."
  main_menu: 
    "What would you like to do?\n
    1. Buy drugs\n
    2. Sell drugs\n
    3. Fly to a new city\n
    4. Go to the bank.\n
    5. Check stats.\n
    6. Hit the gym.\n
    7. Visit the Store."
  bad_selection: "You must choose an available menu option"
  help_menu_title:
    "? HELP ?"
  help_menu:
    "Dopewars help\n? - Displays this menu\nWhen given options, they are usually numbers\n"
  stats_title:
    "* STATS *"
  check_stats_menu: 
    "**********************\n******* STATS ********\n**********************"
  bank_title:
    "$ BANK $"
  bank_menu: 
    "Welcome to the swiss bank exchange.\nChoose an option.\n
    1. Take out a loan.\n
    2. Pay onto a loan.\n
    3. Put money in savings.\n
    4. Take money from savings.\n
    5. Leave"
  airport_title:
    "> AIRPORT <"
  airport_menu:
    "You are currently in %{current_city}.\nWhich City would you like to fly to?\n%{city_options}"
  sellers_title:
    "SELL DRUGS"
  sellers_menu:
    "Which of your drugs would you like to sell?"
  buyers_title:
    "BUY DRUGS"
  buyers_menu:
    "Which of these drugs would you like to buy?"
  gym_title:
    "i_ GYM _i"
  gym_menu:
    "Welcome Silver Gloves Gym\nChoose an option.\n
    1. Work out\n
    2. Leave"
  store_title:
    "$ STORE $"
  store_main_menu:
    "Welcome to the Bad Mofo's Store.\n
    1. Purchase item\n
    2. Leave"
  store_items_menu:
    ""
  player_gained_level:
    "Wow! That was an awesome workout. You're now level %{level}.\n%{new_stats}"
  battle_title:
    "X BATTLE X"
  killed_agent:
    "Congrats, %{name}! You have killed a DEA agent. You have earned a bonus of $%{bonus_amount}. Be on the lookout, you're wanted internationally now.\n\n"
  awareness_notice:
    "People are starting to notice you. If you stay in %{city} for too long, agents may catch on.\n\n"
  high_awareness_notice:
    "You have been spotted by a few people. Agents have been alerted of your location.\n You should fly to a new city before you're caught!\n\n"